## NumPy - Numeric Python

In [47]:
# To install numpy is not installed in the system.
!pip install numpy

In [2]:
import numpy as np

In [51]:
# Ways to initialise array using lists

a1 = np.array([1,2,3,4,5])
a1
type(a1)

numpy.ndarray

In [53]:
a2 = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
a2
type(a2)

numpy.ndarray

In [60]:
# Accessing elements of array

a1[2]
a2[1][0]

4

In [3]:
# 1D array, 2D array, ndarray, vector, matrix

## 1,2,n dimentional array. 1d-Vector, 2d- Matrix, 3d and more - Tensor.
## Array is fixed type container of the sam size and type.The number of dimentions and items in an araay is defined by its shape

a01 = np.array([[[[[[[[[[1,2]]]]]]]]]])
a02 = np.array([[1,2], [2,3]])
a03 = np.array([[[ [1,2], [2,3], [4,5] ]]])
a04 = np.array([ [1,2], [2,3], [4,5],[5,6] ])

a04.ndim

# Therefore the square braket determines the dimentional of the array and not the elements inside it.

2

In [81]:
a3 = np.zeros(5)
a3
a3.ndim

1

In [72]:
a4 = np.ones(10, dtype = int)
a4

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [74]:
a5 = np.empty(5)
a5

array([1.03977794e-312, 2.33419537e-312, 2.22809558e-312, 8.34438346e-308,
       3.56175136e-317])

In [77]:
a6 = np.arange(25)
a6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [78]:
a7 = np.arange(1,19,2)
a7

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [109]:
a8 = np.linspace(0,10,20, dtype = int )

In [110]:
a8

array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
        8,  9, 10])

In [4]:
a8_1 = np.eye(4,3, dtype = int) # Identity matrix.
a8_1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [198]:
a8_2 = np.diag([1,2,3,4]) # Diagonal elemements
a8_2

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [5]:
# Adding , removing and sorting elements

a9 = np.array([5,4,3,2,1,1,1,7,8,9,0,100])
a9

array([  5,   4,   3,   2,   1,   1,   1,   7,   8,   9,   0, 100])

In [126]:
np.sort(a9)

array([  0,   1,   1,   1,   2,   3,   4,   5,   7,   8,   9, 100])

In [6]:
a10 = np.arange(1,10,1)
a11 = np.arange(11,20,1)

In [7]:
a10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a11

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.concatenate([a10,a11])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [10]:
a10[0] = 100

In [11]:
a12 = np.arange(10)
a12

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a12[1:8:2]

array([1, 3, 5, 7])

In [14]:
# Shape, size and reshape of an array

a12

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
a12.shape

(10,)

In [142]:
a12.size

10

In [143]:
a12.ndim

1

In [144]:
a12.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [145]:
a12.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [146]:
a12.reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [148]:
# Creating array from existing arrays

a13 = np.arange(20)
a13

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [149]:
a13_1 = a13[10:19]
a13_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [151]:
# Array Stacking

a14 = np.array([[1,2], [3,4]])
a15 = np.array([[10,20], [30,40]])

In [152]:
a14

array([[1, 2],
       [3, 4]])

In [153]:
a15

array([[10, 20],
       [30, 40]])

In [155]:
np.vstack((a14,a15))

array([[ 1,  2],
       [ 3,  4],
       [10, 20],
       [30, 40]])

In [156]:
np.hstack((a14,a15))

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40]])

In [200]:
# Basic array operations

a16 = np.array([1,2])
a17 = np.ones(2, dtype = int)

In [168]:
a16

array([1, 2])

In [169]:
a17

array([1, 1])

In [162]:
a16+a17

array([2, 3])

In [163]:
a16-a17

array([0, 1])

In [201]:
a16*a17

array([1, 2])

In [202]:
a16.dot(a17)

3

In [165]:
a16/a17

array([1., 2.])

In [167]:
a16.sum()

3

In [171]:
a17 = np.array([[1,2,3], [10,20,30]])

In [172]:
np.sum(a17)

66

In [174]:
np.sum(a17, axis = 0)

array([11, 22, 33])

In [175]:
np.sum(a17, axis = 1)

array([ 6, 60])

In [176]:
a17

array([[ 1,  2,  3],
       [10, 20, 30]])

In [177]:
a17+1

array([[ 2,  3,  4],
       [11, 21, 31]])

In [178]:
a17*2

array([[ 2,  4,  6],
       [20, 40, 60]])

In [180]:
a17.max()

30

In [191]:
a17.max(axis = 1)

array([ 3, 30])

In [192]:
a17.max(axis = 0)

array([10, 20, 30])

In [181]:
a17.min()

1

In [182]:
a17.mean()

11.0

In [193]:
a17.argmin()

0

In [194]:
a17.argmax()

5

In [183]:
a17.std()

10.708252269472673

In [190]:
a17[0,2]

3

In [203]:
#Random number generation

a18 = np.random.rand(3,2)

In [204]:
a18

array([[0.96617189, 0.91852274],
       [0.61429371, 0.02004032],
       [0.49779949, 0.61531025]])

In [206]:
# Unique items

a19 = np.array([1,1,1,2,3,4,5,6,6,6,7])

In [207]:
np.unique(a19)

array([1, 2, 3, 4, 5, 6, 7])

In [208]:
np.unique(a19, return_index = True)

(array([1, 2, 3, 4, 5, 6, 7]),
 array([ 0,  3,  4,  5,  6,  7, 10], dtype=int64))

In [215]:
# 3 ways of transposing

a20 = np.array([[1,2,3], [4,5,6]])

In [218]:
a20

array([[1, 2, 3],
       [4, 5, 6]])

In [221]:
a21 = a20.reshape(3,2)
a21

array([[1, 2],
       [3, 4],
       [5, 6]])

In [222]:
a20.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [224]:
a20.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [227]:
# Array reversing

a21 = np.arange(10)

In [228]:
a21

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [231]:
a22 = np.flip(a21)

In [232]:
a22

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [17]:
# Reshaping and flattening multidimentional array

a23 = np.array([[[1,2], [3,4], [5,6]]])

In [24]:
a23

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [19]:
a23.flatten() # No change to the parent array

array([1, 2, 3, 4, 5, 6])

In [23]:
a23.ravel()

array([1, 2, 3, 4, 5, 6])

In [25]:
a23

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [253]:
x = np.arange(16).reshape((4,4))

In [254]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [255]:
np.diag(x)

array([ 0,  5, 10, 15])

In [256]:
np.diag(x, k = 0)

array([ 0,  5, 10, 15])

In [257]:
np.diag(x, k = 1)

array([ 1,  6, 11])

In [258]:
np.diag(x, k = 2)

array([2, 7])

In [259]:
np.diag(x, k = -1)

array([ 4,  9, 14])

In [260]:
np.diag(x, k = -2)

array([ 8, 13])

In [37]:
## MATRIX FORMATION  - Matrix is a subclass of array.

# Vector to matrix
a3 = np.array([[1,2], [3,4]])
type(a3)

numpy.ndarray

In [38]:
a31 = np.mat(a3)
a31
type(a31)

numpy.matrix

In [43]:
# Direct matrix creation
a32 = np.mat('1,2;3,4')
a32

matrix([[1, 2],
        [3, 4]])

In [44]:
a33 = np.mat('1,2,3; 4,5,6; 7,8,9')
a33

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [45]:
a34 = np.mat([[1,2], [3,4]])
a34

matrix([[1, 2],
        [3, 4]])

In [47]:
a35 = np.mat([[1,2,3], [4,5,6], [7,8,9]])
a35

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [49]:
a35.transpose()

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [50]:
a35.diagonal()

matrix([[1, 5, 9]])

In [56]:
# Deep vs. Shallow copy

a4 = np.mat([[1,2,3], [4,5,6]])
a4

matrix([[1, 2, 3],
        [4, 5, 6]])

In [52]:
# Shallow copy
a41 = a4

In [53]:
a41[0,2] = 30

In [54]:
a41

matrix([[ 1,  2, 30],
        [ 4,  5,  6]])

In [55]:
a4  #Thus with the change in the a44, the parent variable a4 also gets changed. 

matrix([[ 1,  2, 30],
        [ 4,  5,  6]])

In [57]:
# Deep copy

a42 = a4.copy()

In [58]:
a42[0,2] = 30
a42

matrix([[ 1,  2, 30],
        [ 4,  5,  6]])

In [59]:
a4 3 #The parent variable remains intact !

matrix([[1, 2, 3],
        [4, 5, 6]])